version: 3.0.{build}-beta
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- cmd: dotnet restore ./Web/QueryTree.csproj --verbosity m
build_script:
- cmd: dotnet publish -c Release ./Web/QueryTree.csproj -o ./dist
after_build:
- cmd: 7z c QueryTree.zip dist/
artifacts:
- path: QueryTree.zip
  name: QueryTree
deploy: off