version: 3.0.{build}-beta
branches:
  only:
  - master
image: Visual Studio 2017
before_build:
- cmd: dotnet restore ./Web/QueryTree.csproj --verbosity m
build_script:
- cmd: dotnet publish --framework netcoreapp2.0 -c Release ./Web/QueryTree.csproj -o ./dist
after_build:
- cmd: 7z a QueryTree.zip %APPVEYOR_BUILD_FOLDER%/Web/dist/*
- cmd: 7z a QueryTree.zip %APPVEYOR_BUILD_FOLDER%/README.md
before_test:
- cmd: dotnet build ./Tests/Tests.csproj
test:
  assemblies:
    only:
      - ./Tests/**/*.dll
artifacts:
- path: QueryTree.zip
  name: QueryTree
deploy:
- provider: GitHub
  auth_token:
    secure: TTh+pPXrzHRE/f+BmUcTJOsPv17iIw63BJkfDD6SFtmbYp2Wa6hULINuu0wk6yyv